### ISSUE TITLE
Permission denied to access property \"document\" on cross-origin object

### ISSUE THREAD

**Issue by MakeApps** [IntuitDeveloper/HelloWorld-PHP#1]
DOMException
code: 18
columnNumber: 0
data: null
filename: "https://my domain with SSL/quick_book/"
lineNumber: 33
message: "Permission denied to access property \"document\" on cross-origin object"

Code from Browser...

`
var win = window.open(url, 'connectPopup', parameters);
var pollOAuth = window.setInterval(function () {

   try {
    
   if (win.document.URL.indexOf("code") != -1) {
   window.clearInterval(pollOAuth);
   // win.close();
   location.reload();
   }
   } catch (e) {
   console.log(e)
   }
   }, 100);

`

**Comment by user-name-is-taken** [comment]
How was this resolved?

Edit: I was using `127.0.0.1` instead of `localhost` as the url in my browser
